import numpy as np
x = np.arange(0,20)
print("Original array:")
print(x)
numb_1 = np.mean(x)
num_2 = np.average(x)
assert np.allclose(numb_1, num_2)
print("Mean: ", numb_1)
numb_1 = np.std(x)
num_2 = np.sqrt(np.mean((x - np.mean(x)) ** 2 ))
assert np.allclose(numb_1, num_2)
print("std: ", 1)
numb_1= np.var(x)
num_2 = np.mean((x - np.mean(x)) ** 2 )
assert np.allclose(numb_1, num_2)
print("\nvariance: ", numb_1)
